
user:
    type:     annotation
    resource: SyedOmair\Bundle\AppBundle\Controller\UserController

catalog:
    type:     annotation
    resource: SyedOmair\Bundle\AppBundle\Controller\CatalogController
