services:
    cv_auth.security.authentication.provider:
        class: CrowdValley\Bundle\ApiBundle\Security\Authentication\Provider\CVAuthProvider
        arguments: ["", "%kernel.cache_dir%/security/nonces", '@service_container']

    cv_auth.security.authentication.listener:
        class: CrowdValley\Bundle\ApiBundle\Security\Firewall\CVAuthListener
        arguments: ["@security.token_storage", "@security.authentication.manager"]

    PBKDF2_encoder:
        class: CrowdValley\Bundle\ApiBundle\Service\PBKDF2
        arguments: ['@service_container']

    kernel.listener.cv_access_listener:
        class: CrowdValley\Bundle\ApiBundle\EventListener\CVAccessListener
        arguments: ["@service_container", "@security.context", "@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 5 }

    kernel.listener.cv_api_log_listener:
        class: CrowdValley\Bundle\ApiBundle\EventListener\CVApiLogListener
        arguments: [@kernel]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onControllerRequest }
